[package]
name = "HexoTK"
version     = "0.1.0"
authors     = ["Weird Constructor <weirdconstructor@gmail.com>"]
edition     = "2018"
license     = "AGPL-3.0-or-later"
description = "HexoTK - A GUI Toolkit for Audio Plugins"

[lib]
name = "hexotk"

[dependencies]
femtovg            = { git = "https://github.com/femtovg/femtovg", rev = "9c5de268cd1f85d9e32d20c8a37341709c92bdb5" }
raw-gl-context     = { git = "https://github.com/glowcoil/raw-gl-context" }
baseview           = { git = "https://github.com/WeirdConstructor/baseview.git", branch = "fix_resize_problems" }
keyboard-types     = { version = "0.5.0", default-features = false }
raw-window-handle  = "0.3"
gl                 = "0.14.0"
glutin             = "0.24.1"
