[package]
name        = "hexotk"
version     = "0.5.0"
authors     = ["Weird Constructor <weirdconstructor@m8geil.de>"]
edition     = "2018"
license     = "AGPL-3.0-or-later"
description = "HexoTK - A GUI Toolkit for Audio Plugins"

[lib]
name = "hexotk"

[features]
default=[]
driver=[]

[dependencies]
#hexodsp            = { git = "https://github.com/WeirdConstructor/HexoDSP.git" }
hexodsp             = { path = "../hexodsp" }
femtovg            = { git = "https://github.com/femtovg/femtovg" }
raw-gl-context     = { git = "https://github.com/glowcoil/raw-gl-context" }
#baseview           = { git = "https://github.com/WeirdConstructor/baseview.git", branch = "fix_resize_problems" }
baseview           = { git = "https://github.com/glowcoil/baseview.git", branch = "copy-from-parent" }
keyboard-types     = { version = "0.5.0", default-features = false }
raw-window-handle  = "0.3"
gl                 = "0.14.0"
#glutin             = "0.24.1"
